### ISSUE TITLE
USB support on Sierra?

### ISSUE THREAD

**Issue by ITAInc** [tambovchanin/macos-sierra-sane-binaries#4]
I have successfully installed this, but it is not finding any scanners. 
sane-find-scanner also doesn't find anything.
scan image shows "no SANE devices found"

System Information shows (under usb)
EPSON Scanner:

  Product ID:	0x0129
  Vendor ID:	0x04b8  (Seiko Epson Corp.)
  Version:	1.00
  Speed:	Up to 480 Mb/sec
  Manufacturer:	EPSON
  Location ID:	0x14530000 / 3
  Current Available (mA):	500
  Extra Operating Current (mA):	0

Any thoughts would be appreciated.

**Comment by tambovchanin** [comment]
Recompile with libusb
